### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by goertzenator** [ignatov/intellij-erlang#471]
Consider supporting the Elixir language described here:  http://elixir-lang.org/ 

Business case: If you believe Dave Thomas (of Ruby and Pragmatic Programmer fame), Elixir is an important up and coming language.  If it does become popular, a good Elixir plugin would surely drive IntelliJ sales.  By having a good Erlang plugin, I think you are already halfway to having good Elixir support.

**Comment by jlirochon** [comment]
+1 but to me, the killer feature would be the debugger. As @KronicDeth said other syntax highlighting projects exists for Elixir. But no debugger at all ?

Since intellij-erlang seems to wrap erlang debugger, and I know we can use this debugger to debug Elixir code (successfully tested using `Quaff.Debug` module from https://github.com/qhool/quaff on Elixir 1.0.4), a convergence between intellij-erlang and intellij-elixir may be a good idea.

**Comment by KronicDeth** [comment]
@jlirochon https://github.com/KronicDeth/intellij-elixir/issues/81 already existed to add debugger support to intellij-elixir using intellij-erlang's debugger. @mvbaffa may be working on it in https://github.com/KronicDeth/intellij-elixir/issues/124 if I can explain the testing and development setup correctly for them to work on it.

**Comment by smeevil** [comment]
yes please !

**Comment by qertoip** [comment]
+1 the JetBrains Elixir IDE simply must happen :)

**Comment by kvakvs** [comment]
Please refer to https://github.com/KronicDeth/intellij-elixir
Closing this
