### ISSUE TITLE
Can not run helloWorld

### ISSUE THREAD

**Issue by hhimanshu** [ignatov/intellij-erlang#552]
my code looks like  

```
-module(helloWorld).
-author("harith").

%% API
-export([start/0]).

start() -> io:fwrite("hello, world\n").

```
my Erlang Console looks like  
![screen shot 2015-01-02 at 7 04 34 am](https://cloud.githubusercontent.com/assets/6589036/5596900/a610b136-924d-11e4-87b9-73f9bde4f78f.png)

But when I try to run my program on console, it fails
![screen shot 2015-01-02 at 7 05 25 am](https://cloud.githubusercontent.com/assets/6589036/5596904/bfb6d552-924d-11e4-81b7-afdff142f9eb.png)

What's wrong here?
![screen shot 2015-01-02 at 7 05 50 am](https://cloud.githubusercontent.com/assets/6589036/5596905/cc31d8f4-924d-11e4-997c-1ffdf71d39a4.png)

**Comment by deadok22** [comment]
Hi @hhimanshu!

Take a look at a code path your console is run with (the first line in your console output).

You have selected your console to be run with code path of module ```erlang``` which means it will start with this module's build output path included in code path. 

And apparently, you want your source path to be included in code path so that you could compile it from the console. The solution would be to add ```-pa /Users/harith/code/IdeaProjects/others/programmingErlang/erlang/src/``` as a shell argument. Or, you can use IntelliJ's ```Make Project``` action ('Build' -> 'Make Project') and run your code without compiling it.

**Comment by hhimanshu** [comment]
Thanks, that works @deadok22
