### ISSUE TITLE
Erlang.mk support

### ISSUE THREAD

**Issue by wcummings** [ignatov/intellij-erlang#567]
How involved would supporting erlang.mk [1] be? Is it just a matter of parsing out the urls from the makefile on import and invoking "make" instead of rebar to build it?

[1] https://github.com/ninenines/erlang.mk

**Comment by deadok22** [comment]
Hi @wcummings,

You're right, basic erlang.mk support would only require project import and parsing makefiles in order to detect include directories/parsetransforms/subprojects/compiler flags. Secondly, we'll need to build the project, so it should be something like invoking 'make' instead of 'rebar compile'. The third thing would be supporting erlang.mk plugins (e.g. EUnit plugin to run tests in IDE). The fourth would be all the other fancy stuff there is, like creating template projects. 

Sounds pretty simple, but as it often is, devil's in the details. Here are some of the issues from the top of my head:
* Erlang.mk is make-based, which means users might want to use build targets other than the ones specified by erlang.mk. 
* Also there can be arbitrary scripts invoked from makefiles used. This means we'll never make a 100% working solution, but we can support common cases.
* We'll also have to deal with makefile inclusions.
* I don't know whether erlang.mk can be used on Windows, - if it is, we'll have to support that as well.

I haven't tried to use Erlang.mk and all I've written above is based on my impressions from reading erlang.mk readme file. 

As you see, there is a lot of work, but each piece of it is granular, so erlang.mk support can be brought in small steps.

I hope I didn't kill your enthusiasm about it =)

**Comment by michaelklishin** [comment]
:+1: to erlang.mk support. It is an excellent tool.
