### ISSUE TITLE
beam file being deleted by IdeaJ

### ISSUE THREAD

**Issue by myles-mcdonnell** [ignatov/intellij-erlang#584]
Hi

riakc is one of my application deps.  I have observed IdeaJ (confirmed using auditctl) delete the deps/riakc/ebin/riakc_pb_socket.beam file seemingly at random.  It does not delete the one other beam file at that location and it is not during any operation, such as build (I use rebar in a shell, only using IDJ for code edit).

IDJ 14.1.141.177 ::  IDJ-ERL 0.5.11

Is this a known issue? 

Thanks
Myles

**Comment by deadok22** [comment]
Hi @myles-mcdonnell!

Sounds weird. I'd expect it to delete files in output directories in case you have ```Clear output directory on rebuild``` checkbox checked. Otherwise it shouldn't do anything with your output directory content.

Please, share your log files and build log files just in case. You can find log files at 'Help' -> 'Show Log In ...'.

**Comment by myles-mcdonnell** [comment]
..sorry, I had neglected to disable 'make project automatically'. My bad. Please close or delete issue.

**Comment by deadok22** [comment]
Anyway, it's surprising that it did not delete all files if it deleted anything at all.
