### ISSUE TITLE
IntelliJ Erlang plugin ready for development and/or production usage?

### ISSUE THREAD

**Issue by conradwt** [ignatov/intellij-erlang#681]
Hi, I have been watching the commits for several months and all the contributors are doing great work.  Thus, I just wanted to check the current state of the IntelliJ Erlang plugin.  Is it ready for development and/or production use at this time or should I wait a bit?  I ask the questions because I would like to adopt the IntelliJ Erlang plugin for Erlang application development.

**Comment by deadok22** [comment]
Hi @conradwt!

You should decide on it yourself, because it really depends on your expectations. Some people use it as their primary Erlang IDE for a couple of years already, and the plugin has matured and improved since then.

So, I'd suggest you go give it a try, read some stuff on the internet, watch a couple of videos of @ignatov and me live coding in it, and decide whether it suits you or not.

I would definitely use it if I was to develop applications in Erlang myself.

**Comment by conradwt** [comment]
@deadok22 Thanks for the feedback and I'll give it a try this weekend.
