### ISSUE TITLE
Can't get auto popup menu when typing in string

### ISSUE THREAD

**Issue by johnzeng** [ignatov/intellij-erlang#803]
Can I get completion popup menu when typing string?

For example, when typing

```
maps:get(<<"some-key">>, MapTerm),
```

I don't get any thing when typing "some-key", any idea to do that ?

**Comment by NobbZ** [comment]
I haven't seen any IDE so far which completed in string literals. I've seen spellcheckers though, but thats probably not what you want.

**Comment by johnzeng** [comment]
I am vim user and looking for a tool to replace vim. vim completes in string and comment. I don't know why IDE doesn't provide it, I think providing some words from current buffer or opened buffer is really helpful for me. Is it impossible in IDE?

**Comment by NobbZ** [comment]
I wouldn't say its impossible, but uncommon.

I've used vim myself for some time, also some other semi-smart editors which provided context unaware completion from the buffer. Most of the time it was in my way instead of helping me.

I'd try to deactivate such a feature as soon as I do realize it.

Perhaps avoiding binary keys for the map and using atoms instead is a cleaner approach?

**Comment by ignatov** [comment]
You can use **Alt + /** or **Alt + Shift + /** for such kind of completion.

**Comment by johnzeng** [comment]
It's about parsing json and xml data, so they are there and I use them quite frequently.  Alt + / and Alt + shift + / can find something, but not enough for me ... hmmm..... Maybe I should get used to it???

**Comment by NobbZ** [comment]
If the structure of the input is well known enough to hardcode the keys, then transform them into atoms while parsing the input. This will probably even have some performance and memory benefits. I'm not sure though if atoms are completed in a better way than string literals ;)

It's a long time since I used this plugin (or programmed erlang). I really should do something again?

**Comment by ignatov** [comment]
@NobbZ 
> I'm not sure though if atoms are completed in a better way than string literals ;)

During the indexing process, we're collecting all atom names in the whole project and can show them all after.

> It's a long time since I used this plugin (or programmed erlang). I really should do something again?

It's up to you :)

**Comment by ignatov** [comment]
@johnzeng For sure, it's more or less like vim completion by tokens in all open buffers.

**Comment by johnzeng** [comment]
I am closing this issue because I think I was using erlang in a wrong way, I should use a macro to replace the string, so popup when typing string should be useless in a language related plugin.
