### ISSUE TITLE
Intellij 2019.2 support

### ISSUE THREAD

**Issue by algo4** [ignatov/intellij-erlang#862]
The new version Intellij 2019.2 has been released, please update the plugin to make it works with the latest intellij. I really appreciate your work.

**Comment by raz-adroll** [comment]
Not a java expert here but I was checking if I can do it by myself and it seems that Jetbrains hasn't updated the dependencies so that we can build the new version https://www.jetbrains.com/intellij-repository/releases

**Comment by JakaBac** [comment]
With the recent commits the plugin works with 2019.2, but since some tests fail the latest prerelease build was not updated.

You can build the plugin yourself by cloning the repo and doing:
`gradle buildPlugin`

If you don't want to mess with building the plugin you can use my build:
[intellij-erlang-0.11.SNAPSHOT.zip](https://github.com/ignatov/intellij-erlang/files/3434400/intellij-erlang-0.11.SNAPSHOT.zip)

**Comment by heyoka** [comment]
Thank you, works now !

**Comment by algo4** [comment]
Thank you
